stages:
  - lint

python:lint:
  stage: lint
  image: python:3.10-slim
  before_script:
    - pip install flake8
  script:
    - flake8 sdk/python/src/ --count --exclude=*_pb2.py,*_pb2_grpc.py --select=E9,F63,F7,F82 --show-source --statistics
    - flake8 sdk/python/src/ --count --exclude=*_pb2.py,*_pb2_grpc.py --exit-zero --max-complexity=10 --max-line-length=127 --statistics
