// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: dbrouter.proto

package dbrouter

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_dbrouter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dbrouter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_dbrouter_proto_rawDescGZIP(), []int{0}
}

type ConnectionStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Enabled       bool                   `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Host          string                 `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	Port          string                 `protobuf:"bytes,4,opt,name=port,proto3" json:"port,omitempty"`
	Database      string                 `protobuf:"bytes,5,opt,name=database,proto3" json:"database,omitempty"`
	Error         string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionStatus) Reset() {
	*x = ConnectionStatus{}
	mi := &file_dbrouter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionStatus) ProtoMessage() {}

func (x *ConnectionStatus) ProtoReflect() protoreflect.Message {
	mi := &file_dbrouter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionStatus.ProtoReflect.Descriptor instead.
func (*ConnectionStatus) Descriptor() ([]byte, []int) {
	return file_dbrouter_proto_rawDescGZIP(), []int{1}
}

func (x *ConnectionStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ConnectionStatus) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *ConnectionStatus) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *ConnectionStatus) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

func (x *ConnectionStatus) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *ConnectionStatus) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type HealthCheckResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OverallHealthy bool                   `protobuf:"varint,1,opt,name=overall_healthy,json=overallHealthy,proto3" json:"overall_healthy,omitempty"`
	Postgres       *ConnectionStatus      `protobuf:"bytes,2,opt,name=postgres,proto3" json:"postgres,omitempty"`
	Mongo          *ConnectionStatus      `protobuf:"bytes,3,opt,name=mongo,proto3" json:"mongo,omitempty"`
	Redis          *ConnectionStatus      `protobuf:"bytes,4,opt,name=redis,proto3" json:"redis,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_dbrouter_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dbrouter_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_dbrouter_proto_rawDescGZIP(), []int{2}
}

func (x *HealthCheckResponse) GetOverallHealthy() bool {
	if x != nil {
		return x.OverallHealthy
	}
	return false
}

func (x *HealthCheckResponse) GetPostgres() *ConnectionStatus {
	if x != nil {
		return x.Postgres
	}
	return nil
}

func (x *HealthCheckResponse) GetMongo() *ConnectionStatus {
	if x != nil {
		return x.Mongo
	}
	return nil
}

func (x *HealthCheckResponse) GetRedis() *ConnectionStatus {
	if x != nil {
		return x.Redis
	}
	return nil
}

type ListDatabasesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDatabasesRequest) Reset() {
	*x = ListDatabasesRequest{}
	mi := &file_dbrouter_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDatabasesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDatabasesRequest) ProtoMessage() {}

func (x *ListDatabasesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dbrouter_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDatabasesRequest.ProtoReflect.Descriptor instead.
func (*ListDatabasesRequest) Descriptor() ([]byte, []int) {
	return file_dbrouter_proto_rawDescGZIP(), []int{3}
}

type ListDatabasesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Databases     []string               `protobuf:"bytes,1,rep,name=databases,proto3" json:"databases,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDatabasesResponse) Reset() {
	*x = ListDatabasesResponse{}
	mi := &file_dbrouter_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDatabasesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDatabasesResponse) ProtoMessage() {}

func (x *ListDatabasesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dbrouter_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDatabasesResponse.ProtoReflect.Descriptor instead.
func (*ListDatabasesResponse) Descriptor() ([]byte, []int) {
	return file_dbrouter_proto_rawDescGZIP(), []int{4}
}

func (x *ListDatabasesResponse) GetDatabases() []string {
	if x != nil {
		return x.Databases
	}
	return nil
}

type CreateDatabaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDatabaseRequest) Reset() {
	*x = CreateDatabaseRequest{}
	mi := &file_dbrouter_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDatabaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDatabaseRequest) ProtoMessage() {}

func (x *CreateDatabaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dbrouter_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDatabaseRequest.ProtoReflect.Descriptor instead.
func (*CreateDatabaseRequest) Descriptor() ([]byte, []int) {
	return file_dbrouter_proto_rawDescGZIP(), []int{5}
}

func (x *CreateDatabaseRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateDatabaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDatabaseResponse) Reset() {
	*x = CreateDatabaseResponse{}
	mi := &file_dbrouter_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDatabaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDatabaseResponse) ProtoMessage() {}

func (x *CreateDatabaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dbrouter_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDatabaseResponse.ProtoReflect.Descriptor instead.
func (*CreateDatabaseResponse) Descriptor() ([]byte, []int) {
	return file_dbrouter_proto_rawDescGZIP(), []int{6}
}

func (x *CreateDatabaseResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateDatabaseResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListTablesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Database      string                 `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTablesRequest) Reset() {
	*x = ListTablesRequest{}
	mi := &file_dbrouter_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTablesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTablesRequest) ProtoMessage() {}

func (x *ListTablesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dbrouter_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTablesRequest.ProtoReflect.Descriptor instead.
func (*ListTablesRequest) Descriptor() ([]byte, []int) {
	return file_dbrouter_proto_rawDescGZIP(), []int{7}
}

func (x *ListTablesRequest) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

type ListTablesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Database      string                 `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	Tables        []string               `protobuf:"bytes,2,rep,name=tables,proto3" json:"tables,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTablesResponse) Reset() {
	*x = ListTablesResponse{}
	mi := &file_dbrouter_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTablesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTablesResponse) ProtoMessage() {}

func (x *ListTablesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dbrouter_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTablesResponse.ProtoReflect.Descriptor instead.
func (*ListTablesResponse) Descriptor() ([]byte, []int) {
	return file_dbrouter_proto_rawDescGZIP(), []int{8}
}

func (x *ListTablesResponse) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *ListTablesResponse) GetTables() []string {
	if x != nil {
		return x.Tables
	}
	return nil
}

type ExecuteQueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Database      string                 `protobuf:"bytes,2,opt,name=database,proto3" json:"database,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteQueryRequest) Reset() {
	*x = ExecuteQueryRequest{}
	mi := &file_dbrouter_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteQueryRequest) ProtoMessage() {}

func (x *ExecuteQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dbrouter_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteQueryRequest.ProtoReflect.Descriptor instead.
func (*ExecuteQueryRequest) Descriptor() ([]byte, []int) {
	return file_dbrouter_proto_rawDescGZIP(), []int{9}
}

func (x *ExecuteQueryRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *ExecuteQueryRequest) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

type QueryResultRow struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Fields        map[string]*structpb.Value `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResultRow) Reset() {
	*x = QueryResultRow{}
	mi := &file_dbrouter_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResultRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResultRow) ProtoMessage() {}

func (x *QueryResultRow) ProtoReflect() protoreflect.Message {
	mi := &file_dbrouter_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResultRow.ProtoReflect.Descriptor instead.
func (*QueryResultRow) Descriptor() ([]byte, []int) {
	return file_dbrouter_proto_rawDescGZIP(), []int{10}
}

func (x *QueryResultRow) GetFields() map[string]*structpb.Value {
	if x != nil {
		return x.Fields
	}
	return nil
}

type ExecuteQueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Columns       []string               `protobuf:"bytes,1,rep,name=columns,proto3" json:"columns,omitempty"`
	Rows          []*QueryResultRow      `protobuf:"bytes,2,rep,name=rows,proto3" json:"rows,omitempty"`
	Count         int64                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	RowsAffected  int64                  `protobuf:"varint,4,opt,name=rows_affected,json=rowsAffected,proto3" json:"rows_affected,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteQueryResponse) Reset() {
	*x = ExecuteQueryResponse{}
	mi := &file_dbrouter_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteQueryResponse) ProtoMessage() {}

func (x *ExecuteQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dbrouter_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteQueryResponse.ProtoReflect.Descriptor instead.
func (*ExecuteQueryResponse) Descriptor() ([]byte, []int) {
	return file_dbrouter_proto_rawDescGZIP(), []int{11}
}

func (x *ExecuteQueryResponse) GetColumns() []string {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *ExecuteQueryResponse) GetRows() []*QueryResultRow {
	if x != nil {
		return x.Rows
	}
	return nil
}

func (x *ExecuteQueryResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ExecuteQueryResponse) GetRowsAffected() int64 {
	if x != nil {
		return x.RowsAffected
	}
	return 0
}

func (x *ExecuteQueryResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SelectDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Database      string                 `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	Table         string                 `protobuf:"bytes,2,opt,name=table,proto3" json:"table,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SelectDataRequest) Reset() {
	*x = SelectDataRequest{}
	mi := &file_dbrouter_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelectDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectDataRequest) ProtoMessage() {}

func (x *SelectDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dbrouter_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectDataRequest.ProtoReflect.Descriptor instead.
func (*SelectDataRequest) Descriptor() ([]byte, []int) {
	return file_dbrouter_proto_rawDescGZIP(), []int{12}
}

func (x *SelectDataRequest) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *SelectDataRequest) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *SelectDataRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type SelectDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Database      string                 `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	Table         string                 `protobuf:"bytes,2,opt,name=table,proto3" json:"table,omitempty"`
	Data          []*QueryResultRow      `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	Count         int64                  `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SelectDataResponse) Reset() {
	*x = SelectDataResponse{}
	mi := &file_dbrouter_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelectDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectDataResponse) ProtoMessage() {}

func (x *SelectDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dbrouter_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectDataResponse.ProtoReflect.Descriptor instead.
func (*SelectDataResponse) Descriptor() ([]byte, []int) {
	return file_dbrouter_proto_rawDescGZIP(), []int{13}
}

func (x *SelectDataResponse) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *SelectDataResponse) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *SelectDataResponse) GetData() []*QueryResultRow {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SelectDataResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type InsertDataRequest struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Database      string                     `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	Table         string                     `protobuf:"bytes,2,opt,name=table,proto3" json:"table,omitempty"`
	Data          map[string]*structpb.Value `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertDataRequest) Reset() {
	*x = InsertDataRequest{}
	mi := &file_dbrouter_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertDataRequest) ProtoMessage() {}

func (x *InsertDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dbrouter_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertDataRequest.ProtoReflect.Descriptor instead.
func (*InsertDataRequest) Descriptor() ([]byte, []int) {
	return file_dbrouter_proto_rawDescGZIP(), []int{14}
}

func (x *InsertDataRequest) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *InsertDataRequest) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *InsertDataRequest) GetData() map[string]*structpb.Value {
	if x != nil {
		return x.Data
	}
	return nil
}

type InsertDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Database      string                 `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	Table         string                 `protobuf:"bytes,2,opt,name=table,proto3" json:"table,omitempty"`
	InsertedId    string                 `protobuf:"bytes,3,opt,name=inserted_id,json=insertedId,proto3" json:"inserted_id,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertDataResponse) Reset() {
	*x = InsertDataResponse{}
	mi := &file_dbrouter_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertDataResponse) ProtoMessage() {}

func (x *InsertDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dbrouter_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertDataResponse.ProtoReflect.Descriptor instead.
func (*InsertDataResponse) Descriptor() ([]byte, []int) {
	return file_dbrouter_proto_rawDescGZIP(), []int{15}
}

func (x *InsertDataResponse) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *InsertDataResponse) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *InsertDataResponse) GetInsertedId() string {
	if x != nil {
		return x.InsertedId
	}
	return ""
}

func (x *InsertDataResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UpdateDataRequest struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Database      string                     `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	Table         string                     `protobuf:"bytes,2,opt,name=table,proto3" json:"table,omitempty"`
	Id            string                     `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Data          map[string]*structpb.Value `protobuf:"bytes,4,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDataRequest) Reset() {
	*x = UpdateDataRequest{}
	mi := &file_dbrouter_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDataRequest) ProtoMessage() {}

func (x *UpdateDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dbrouter_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDataRequest.ProtoReflect.Descriptor instead.
func (*UpdateDataRequest) Descriptor() ([]byte, []int) {
	return file_dbrouter_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateDataRequest) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *UpdateDataRequest) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *UpdateDataRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateDataRequest) GetData() map[string]*structpb.Value {
	if x != nil {
		return x.Data
	}
	return nil
}

type UpdateDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Database      string                 `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	Table         string                 `protobuf:"bytes,2,opt,name=table,proto3" json:"table,omitempty"`
	Id            string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	RowsAffected  int64                  `protobuf:"varint,4,opt,name=rows_affected,json=rowsAffected,proto3" json:"rows_affected,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDataResponse) Reset() {
	*x = UpdateDataResponse{}
	mi := &file_dbrouter_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDataResponse) ProtoMessage() {}

func (x *UpdateDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dbrouter_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDataResponse.ProtoReflect.Descriptor instead.
func (*UpdateDataResponse) Descriptor() ([]byte, []int) {
	return file_dbrouter_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateDataResponse) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *UpdateDataResponse) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *UpdateDataResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateDataResponse) GetRowsAffected() int64 {
	if x != nil {
		return x.RowsAffected
	}
	return 0
}

type DeleteDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Database      string                 `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	Table         string                 `protobuf:"bytes,2,opt,name=table,proto3" json:"table,omitempty"`
	Id            string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDataRequest) Reset() {
	*x = DeleteDataRequest{}
	mi := &file_dbrouter_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDataRequest) ProtoMessage() {}

func (x *DeleteDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dbrouter_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDataRequest.ProtoReflect.Descriptor instead.
func (*DeleteDataRequest) Descriptor() ([]byte, []int) {
	return file_dbrouter_proto_rawDescGZIP(), []int{18}
}

func (x *DeleteDataRequest) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *DeleteDataRequest) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *DeleteDataRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Database      string                 `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	Table         string                 `protobuf:"bytes,2,opt,name=table,proto3" json:"table,omitempty"`
	Id            string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	RowsAffected  int64                  `protobuf:"varint,4,opt,name=rows_affected,json=rowsAffected,proto3" json:"rows_affected,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDataResponse) Reset() {
	*x = DeleteDataResponse{}
	mi := &file_dbrouter_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDataResponse) ProtoMessage() {}

func (x *DeleteDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dbrouter_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDataResponse.ProtoReflect.Descriptor instead.
func (*DeleteDataResponse) Descriptor() ([]byte, []int) {
	return file_dbrouter_proto_rawDescGZIP(), []int{19}
}

func (x *DeleteDataResponse) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *DeleteDataResponse) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *DeleteDataResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteDataResponse) GetRowsAffected() int64 {
	if x != nil {
		return x.RowsAffected
	}
	return 0
}

type ListMongoDatabasesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMongoDatabasesRequest) Reset() {
	*x = ListMongoDatabasesRequest{}
	mi := &file_dbrouter_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMongoDatabasesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMongoDatabasesRequest) ProtoMessage() {}

func (x *ListMongoDatabasesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dbrouter_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMongoDatabasesRequest.ProtoReflect.Descriptor instead.
func (*ListMongoDatabasesRequest) Descriptor() ([]byte, []int) {
	return file_dbrouter_proto_rawDescGZIP(), []int{20}
}

type ListMongoDatabasesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Databases     []string               `protobuf:"bytes,1,rep,name=databases,proto3" json:"databases,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMongoDatabasesResponse) Reset() {
	*x = ListMongoDatabasesResponse{}
	mi := &file_dbrouter_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMongoDatabasesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMongoDatabasesResponse) ProtoMessage() {}

func (x *ListMongoDatabasesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dbrouter_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMongoDatabasesResponse.ProtoReflect.Descriptor instead.
func (*ListMongoDatabasesResponse) Descriptor() ([]byte, []int) {
	return file_dbrouter_proto_rawDescGZIP(), []int{21}
}

func (x *ListMongoDatabasesResponse) GetDatabases() []string {
	if x != nil {
		return x.Databases
	}
	return nil
}

type ListCollectionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Database      string                 `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCollectionsRequest) Reset() {
	*x = ListCollectionsRequest{}
	mi := &file_dbrouter_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCollectionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCollectionsRequest) ProtoMessage() {}

func (x *ListCollectionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dbrouter_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCollectionsRequest.ProtoReflect.Descriptor instead.
func (*ListCollectionsRequest) Descriptor() ([]byte, []int) {
	return file_dbrouter_proto_rawDescGZIP(), []int{22}
}

func (x *ListCollectionsRequest) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

type ListCollectionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Database      string                 `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	Collections   []string               `protobuf:"bytes,2,rep,name=collections,proto3" json:"collections,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCollectionsResponse) Reset() {
	*x = ListCollectionsResponse{}
	mi := &file_dbrouter_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCollectionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCollectionsResponse) ProtoMessage() {}

func (x *ListCollectionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dbrouter_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCollectionsResponse.ProtoReflect.Descriptor instead.
func (*ListCollectionsResponse) Descriptor() ([]byte, []int) {
	return file_dbrouter_proto_rawDescGZIP(), []int{23}
}

func (x *ListCollectionsResponse) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *ListCollectionsResponse) GetCollections() []string {
	if x != nil {
		return x.Collections
	}
	return nil
}

type InsertDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Database      string                 `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	Collection    string                 `protobuf:"bytes,2,opt,name=collection,proto3" json:"collection,omitempty"`
	Document      *structpb.Struct       `protobuf:"bytes,3,opt,name=document,proto3" json:"document,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertDocumentRequest) Reset() {
	*x = InsertDocumentRequest{}
	mi := &file_dbrouter_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertDocumentRequest) ProtoMessage() {}

func (x *InsertDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dbrouter_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertDocumentRequest.ProtoReflect.Descriptor instead.
func (*InsertDocumentRequest) Descriptor() ([]byte, []int) {
	return file_dbrouter_proto_rawDescGZIP(), []int{24}
}

func (x *InsertDocumentRequest) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *InsertDocumentRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *InsertDocumentRequest) GetDocument() *structpb.Struct {
	if x != nil {
		return x.Document
	}
	return nil
}

type InsertDocumentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Database      string                 `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	Collection    string                 `protobuf:"bytes,2,opt,name=collection,proto3" json:"collection,omitempty"`
	InsertedId    string                 `protobuf:"bytes,3,opt,name=inserted_id,json=insertedId,proto3" json:"inserted_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertDocumentResponse) Reset() {
	*x = InsertDocumentResponse{}
	mi := &file_dbrouter_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertDocumentResponse) ProtoMessage() {}

func (x *InsertDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dbrouter_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertDocumentResponse.ProtoReflect.Descriptor instead.
func (*InsertDocumentResponse) Descriptor() ([]byte, []int) {
	return file_dbrouter_proto_rawDescGZIP(), []int{25}
}

func (x *InsertDocumentResponse) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *InsertDocumentResponse) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *InsertDocumentResponse) GetInsertedId() string {
	if x != nil {
		return x.InsertedId
	}
	return ""
}

type FindDocumentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Database      string                 `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	Collection    string                 `protobuf:"bytes,2,opt,name=collection,proto3" json:"collection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindDocumentsRequest) Reset() {
	*x = FindDocumentsRequest{}
	mi := &file_dbrouter_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindDocumentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindDocumentsRequest) ProtoMessage() {}

func (x *FindDocumentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dbrouter_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindDocumentsRequest.ProtoReflect.Descriptor instead.
func (*FindDocumentsRequest) Descriptor() ([]byte, []int) {
	return file_dbrouter_proto_rawDescGZIP(), []int{26}
}

func (x *FindDocumentsRequest) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *FindDocumentsRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

type MongoDocument struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Fields        map[string]*structpb.Value `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MongoDocument) Reset() {
	*x = MongoDocument{}
	mi := &file_dbrouter_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MongoDocument) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MongoDocument) ProtoMessage() {}

func (x *MongoDocument) ProtoReflect() protoreflect.Message {
	mi := &file_dbrouter_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MongoDocument.ProtoReflect.Descriptor instead.
func (*MongoDocument) Descriptor() ([]byte, []int) {
	return file_dbrouter_proto_rawDescGZIP(), []int{27}
}

func (x *MongoDocument) GetFields() map[string]*structpb.Value {
	if x != nil {
		return x.Fields
	}
	return nil
}

type FindDocumentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Database      string                 `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	Collection    string                 `protobuf:"bytes,2,opt,name=collection,proto3" json:"collection,omitempty"`
	Documents     []*MongoDocument       `protobuf:"bytes,3,rep,name=documents,proto3" json:"documents,omitempty"`
	Count         int64                  `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindDocumentsResponse) Reset() {
	*x = FindDocumentsResponse{}
	mi := &file_dbrouter_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindDocumentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindDocumentsResponse) ProtoMessage() {}

func (x *FindDocumentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dbrouter_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindDocumentsResponse.ProtoReflect.Descriptor instead.
func (*FindDocumentsResponse) Descriptor() ([]byte, []int) {
	return file_dbrouter_proto_rawDescGZIP(), []int{28}
}

func (x *FindDocumentsResponse) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *FindDocumentsResponse) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *FindDocumentsResponse) GetDocuments() []*MongoDocument {
	if x != nil {
		return x.Documents
	}
	return nil
}

func (x *FindDocumentsResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type UpdateDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Database      string                 `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	Collection    string                 `protobuf:"bytes,2,opt,name=collection,proto3" json:"collection,omitempty"`
	Id            string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Update        *structpb.Struct       `protobuf:"bytes,4,opt,name=update,proto3" json:"update,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDocumentRequest) Reset() {
	*x = UpdateDocumentRequest{}
	mi := &file_dbrouter_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDocumentRequest) ProtoMessage() {}

func (x *UpdateDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dbrouter_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDocumentRequest.ProtoReflect.Descriptor instead.
func (*UpdateDocumentRequest) Descriptor() ([]byte, []int) {
	return file_dbrouter_proto_rawDescGZIP(), []int{29}
}

func (x *UpdateDocumentRequest) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *UpdateDocumentRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *UpdateDocumentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateDocumentRequest) GetUpdate() *structpb.Struct {
	if x != nil {
		return x.Update
	}
	return nil
}

type UpdateDocumentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Database      string                 `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	Collection    string                 `protobuf:"bytes,2,opt,name=collection,proto3" json:"collection,omitempty"`
	MatchedCount  int64                  `protobuf:"varint,3,opt,name=matched_count,json=matchedCount,proto3" json:"matched_count,omitempty"`
	ModifiedCount int64                  `protobuf:"varint,4,opt,name=modified_count,json=modifiedCount,proto3" json:"modified_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDocumentResponse) Reset() {
	*x = UpdateDocumentResponse{}
	mi := &file_dbrouter_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDocumentResponse) ProtoMessage() {}

func (x *UpdateDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dbrouter_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDocumentResponse.ProtoReflect.Descriptor instead.
func (*UpdateDocumentResponse) Descriptor() ([]byte, []int) {
	return file_dbrouter_proto_rawDescGZIP(), []int{30}
}

func (x *UpdateDocumentResponse) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *UpdateDocumentResponse) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *UpdateDocumentResponse) GetMatchedCount() int64 {
	if x != nil {
		return x.MatchedCount
	}
	return 0
}

func (x *UpdateDocumentResponse) GetModifiedCount() int64 {
	if x != nil {
		return x.ModifiedCount
	}
	return 0
}

type DeleteDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Database      string                 `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	Collection    string                 `protobuf:"bytes,2,opt,name=collection,proto3" json:"collection,omitempty"`
	Id            string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDocumentRequest) Reset() {
	*x = DeleteDocumentRequest{}
	mi := &file_dbrouter_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDocumentRequest) ProtoMessage() {}

func (x *DeleteDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dbrouter_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDocumentRequest.ProtoReflect.Descriptor instead.
func (*DeleteDocumentRequest) Descriptor() ([]byte, []int) {
	return file_dbrouter_proto_rawDescGZIP(), []int{31}
}

func (x *DeleteDocumentRequest) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *DeleteDocumentRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *DeleteDocumentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteDocumentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Database      string                 `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	Collection    string                 `protobuf:"bytes,2,opt,name=collection,proto3" json:"collection,omitempty"`
	DeletedCount  int64                  `protobuf:"varint,3,opt,name=deleted_count,json=deletedCount,proto3" json:"deleted_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDocumentResponse) Reset() {
	*x = DeleteDocumentResponse{}
	mi := &file_dbrouter_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDocumentResponse) ProtoMessage() {}

func (x *DeleteDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dbrouter_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDocumentResponse.ProtoReflect.Descriptor instead.
func (*DeleteDocumentResponse) Descriptor() ([]byte, []int) {
	return file_dbrouter_proto_rawDescGZIP(), []int{32}
}

func (x *DeleteDocumentResponse) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *DeleteDocumentResponse) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *DeleteDocumentResponse) GetDeletedCount() int64 {
	if x != nil {
		return x.DeletedCount
	}
	return 0
}

type ListKeysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pattern       string                 `protobuf:"bytes,1,opt,name=pattern,proto3" json:"pattern,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListKeysRequest) Reset() {
	*x = ListKeysRequest{}
	mi := &file_dbrouter_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListKeysRequest) ProtoMessage() {}

func (x *ListKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dbrouter_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListKeysRequest.ProtoReflect.Descriptor instead.
func (*ListKeysRequest) Descriptor() ([]byte, []int) {
	return file_dbrouter_proto_rawDescGZIP(), []int{33}
}

func (x *ListKeysRequest) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

type ListKeysResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          []string               `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListKeysResponse) Reset() {
	*x = ListKeysResponse{}
	mi := &file_dbrouter_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListKeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListKeysResponse) ProtoMessage() {}

func (x *ListKeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dbrouter_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListKeysResponse.ProtoReflect.Descriptor instead.
func (*ListKeysResponse) Descriptor() ([]byte, []int) {
	return file_dbrouter_proto_rawDescGZIP(), []int{34}
}

func (x *ListKeysResponse) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *ListKeysResponse) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type SetValueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Ttl           int32                  `protobuf:"varint,3,opt,name=ttl,proto3" json:"ttl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetValueRequest) Reset() {
	*x = SetValueRequest{}
	mi := &file_dbrouter_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetValueRequest) ProtoMessage() {}

func (x *SetValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dbrouter_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetValueRequest.ProtoReflect.Descriptor instead.
func (*SetValueRequest) Descriptor() ([]byte, []int) {
	return file_dbrouter_proto_rawDescGZIP(), []int{35}
}

func (x *SetValueRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetValueRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *SetValueRequest) GetTtl() int32 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

type SetValueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Ttl           int32                  `protobuf:"varint,3,opt,name=ttl,proto3" json:"ttl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetValueResponse) Reset() {
	*x = SetValueResponse{}
	mi := &file_dbrouter_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetValueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetValueResponse) ProtoMessage() {}

func (x *SetValueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dbrouter_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetValueResponse.ProtoReflect.Descriptor instead.
func (*SetValueResponse) Descriptor() ([]byte, []int) {
	return file_dbrouter_proto_rawDescGZIP(), []int{36}
}

func (x *SetValueResponse) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetValueResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *SetValueResponse) GetTtl() int32 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

type GetValueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetValueRequest) Reset() {
	*x = GetValueRequest{}
	mi := &file_dbrouter_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetValueRequest) ProtoMessage() {}

func (x *GetValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dbrouter_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetValueRequest.ProtoReflect.Descriptor instead.
func (*GetValueRequest) Descriptor() ([]byte, []int) {
	return file_dbrouter_proto_rawDescGZIP(), []int{37}
}

func (x *GetValueRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetValueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Ttl           int32                  `protobuf:"varint,3,opt,name=ttl,proto3" json:"ttl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetValueResponse) Reset() {
	*x = GetValueResponse{}
	mi := &file_dbrouter_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetValueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetValueResponse) ProtoMessage() {}

func (x *GetValueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dbrouter_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetValueResponse.ProtoReflect.Descriptor instead.
func (*GetValueResponse) Descriptor() ([]byte, []int) {
	return file_dbrouter_proto_rawDescGZIP(), []int{38}
}

func (x *GetValueResponse) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GetValueResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *GetValueResponse) GetTtl() int32 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

type DeleteKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteKeyRequest) Reset() {
	*x = DeleteKeyRequest{}
	mi := &file_dbrouter_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKeyRequest) ProtoMessage() {}

func (x *DeleteKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dbrouter_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKeyRequest.ProtoReflect.Descriptor instead.
func (*DeleteKeyRequest) Descriptor() ([]byte, []int) {
	return file_dbrouter_proto_rawDescGZIP(), []int{39}
}

func (x *DeleteKeyRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type DeleteKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Deleted       bool                   `protobuf:"varint,2,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteKeyResponse) Reset() {
	*x = DeleteKeyResponse{}
	mi := &file_dbrouter_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKeyResponse) ProtoMessage() {}

func (x *DeleteKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dbrouter_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKeyResponse.ProtoReflect.Descriptor instead.
func (*DeleteKeyResponse) Descriptor() ([]byte, []int) {
	return file_dbrouter_proto_rawDescGZIP(), []int{40}
}

func (x *DeleteKeyResponse) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *DeleteKeyResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

type RedisInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RedisInfoRequest) Reset() {
	*x = RedisInfoRequest{}
	mi := &file_dbrouter_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedisInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedisInfoRequest) ProtoMessage() {}

func (x *RedisInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dbrouter_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedisInfoRequest.ProtoReflect.Descriptor instead.
func (*RedisInfoRequest) Descriptor() ([]byte, []int) {
	return file_dbrouter_proto_rawDescGZIP(), []int{41}
}

type RedisInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DbSize        int64                  `protobuf:"varint,1,opt,name=db_size,json=dbSize,proto3" json:"db_size,omitempty"`
	Info          string                 `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RedisInfoResponse) Reset() {
	*x = RedisInfoResponse{}
	mi := &file_dbrouter_proto_msgTypes[42]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedisInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedisInfoResponse) ProtoMessage() {}

func (x *RedisInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dbrouter_proto_msgTypes[42]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedisInfoResponse.ProtoReflect.Descriptor instead.
func (*RedisInfoResponse) Descriptor() ([]byte, []int) {
	return file_dbrouter_proto_rawDescGZIP(), []int{42}
}

func (x *RedisInfoResponse) GetDbSize() int64 {
	if x != nil {
		return x.DbSize
	}
	return 0
}

func (x *RedisInfoResponse) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

var File_dbrouter_proto protoreflect.FileDescriptor

const file_dbrouter_proto_rawDesc = "" +
	"\n" +
	"\x0edbrouter.proto\x12\bdbrouter\x1a\x1cgoogle/protobuf/struct.proto\"\x14\n" +
	"\x12HealthCheckRequest\"\x9e\x01\n" +
	"\x10ConnectionStatus\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\aenabled\x18\x02 \x01(\bR\aenabled\x12\x12\n" +
	"\x04host\x18\x03 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x04 \x01(\tR\x04port\x12\x1a\n" +
	"\bdatabase\x18\x05 \x01(\tR\bdatabase\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\"\xda\x01\n" +
	"\x13HealthCheckResponse\x12'\n" +
	"\x0foverall_healthy\x18\x01 \x01(\bR\x0eoverallHealthy\x126\n" +
	"\bpostgres\x18\x02 \x01(\v2\x1a.dbrouter.ConnectionStatusR\bpostgres\x120\n" +
	"\x05mongo\x18\x03 \x01(\v2\x1a.dbrouter.ConnectionStatusR\x05mongo\x120\n" +
	"\x05redis\x18\x04 \x01(\v2\x1a.dbrouter.ConnectionStatusR\x05redis\"\x16\n" +
	"\x14ListDatabasesRequest\"5\n" +
	"\x15ListDatabasesResponse\x12\x1c\n" +
	"\tdatabases\x18\x01 \x03(\tR\tdatabases\"+\n" +
	"\x15CreateDatabaseRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"F\n" +
	"\x16CreateDatabaseResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"/\n" +
	"\x11ListTablesRequest\x12\x1a\n" +
	"\bdatabase\x18\x01 \x01(\tR\bdatabase\"H\n" +
	"\x12ListTablesResponse\x12\x1a\n" +
	"\bdatabase\x18\x01 \x01(\tR\bdatabase\x12\x16\n" +
	"\x06tables\x18\x02 \x03(\tR\x06tables\"G\n" +
	"\x13ExecuteQueryRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x1a\n" +
	"\bdatabase\x18\x02 \x01(\tR\bdatabase\"\xa1\x01\n" +
	"\x0eQueryResultRow\x12<\n" +
	"\x06fields\x18\x01 \x03(\v2$.dbrouter.QueryResultRow.FieldsEntryR\x06fields\x1aQ\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05value:\x028\x01\"\xb3\x01\n" +
	"\x14ExecuteQueryResponse\x12\x18\n" +
	"\acolumns\x18\x01 \x03(\tR\acolumns\x12,\n" +
	"\x04rows\x18\x02 \x03(\v2\x18.dbrouter.QueryResultRowR\x04rows\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x03R\x05count\x12#\n" +
	"\rrows_affected\x18\x04 \x01(\x03R\frowsAffected\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\"[\n" +
	"\x11SelectDataRequest\x12\x1a\n" +
	"\bdatabase\x18\x01 \x01(\tR\bdatabase\x12\x14\n" +
	"\x05table\x18\x02 \x01(\tR\x05table\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"\x8a\x01\n" +
	"\x12SelectDataResponse\x12\x1a\n" +
	"\bdatabase\x18\x01 \x01(\tR\bdatabase\x12\x14\n" +
	"\x05table\x18\x02 \x01(\tR\x05table\x12,\n" +
	"\x04data\x18\x03 \x03(\v2\x18.dbrouter.QueryResultRowR\x04data\x12\x14\n" +
	"\x05count\x18\x04 \x01(\x03R\x05count\"\xd1\x01\n" +
	"\x11InsertDataRequest\x12\x1a\n" +
	"\bdatabase\x18\x01 \x01(\tR\bdatabase\x12\x14\n" +
	"\x05table\x18\x02 \x01(\tR\x05table\x129\n" +
	"\x04data\x18\x03 \x03(\v2%.dbrouter.InsertDataRequest.DataEntryR\x04data\x1aO\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05value:\x028\x01\"\x81\x01\n" +
	"\x12InsertDataResponse\x12\x1a\n" +
	"\bdatabase\x18\x01 \x01(\tR\bdatabase\x12\x14\n" +
	"\x05table\x18\x02 \x01(\tR\x05table\x12\x1f\n" +
	"\vinserted_id\x18\x03 \x01(\tR\n" +
	"insertedId\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"\xe1\x01\n" +
	"\x11UpdateDataRequest\x12\x1a\n" +
	"\bdatabase\x18\x01 \x01(\tR\bdatabase\x12\x14\n" +
	"\x05table\x18\x02 \x01(\tR\x05table\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\x129\n" +
	"\x04data\x18\x04 \x03(\v2%.dbrouter.UpdateDataRequest.DataEntryR\x04data\x1aO\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05value:\x028\x01\"{\n" +
	"\x12UpdateDataResponse\x12\x1a\n" +
	"\bdatabase\x18\x01 \x01(\tR\bdatabase\x12\x14\n" +
	"\x05table\x18\x02 \x01(\tR\x05table\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\x12#\n" +
	"\rrows_affected\x18\x04 \x01(\x03R\frowsAffected\"U\n" +
	"\x11DeleteDataRequest\x12\x1a\n" +
	"\bdatabase\x18\x01 \x01(\tR\bdatabase\x12\x14\n" +
	"\x05table\x18\x02 \x01(\tR\x05table\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\"{\n" +
	"\x12DeleteDataResponse\x12\x1a\n" +
	"\bdatabase\x18\x01 \x01(\tR\bdatabase\x12\x14\n" +
	"\x05table\x18\x02 \x01(\tR\x05table\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\x12#\n" +
	"\rrows_affected\x18\x04 \x01(\x03R\frowsAffected\"\x1b\n" +
	"\x19ListMongoDatabasesRequest\":\n" +
	"\x1aListMongoDatabasesResponse\x12\x1c\n" +
	"\tdatabases\x18\x01 \x03(\tR\tdatabases\"4\n" +
	"\x16ListCollectionsRequest\x12\x1a\n" +
	"\bdatabase\x18\x01 \x01(\tR\bdatabase\"W\n" +
	"\x17ListCollectionsResponse\x12\x1a\n" +
	"\bdatabase\x18\x01 \x01(\tR\bdatabase\x12 \n" +
	"\vcollections\x18\x02 \x03(\tR\vcollections\"\x88\x01\n" +
	"\x15InsertDocumentRequest\x12\x1a\n" +
	"\bdatabase\x18\x01 \x01(\tR\bdatabase\x12\x1e\n" +
	"\n" +
	"collection\x18\x02 \x01(\tR\n" +
	"collection\x123\n" +
	"\bdocument\x18\x03 \x01(\v2\x17.google.protobuf.StructR\bdocument\"u\n" +
	"\x16InsertDocumentResponse\x12\x1a\n" +
	"\bdatabase\x18\x01 \x01(\tR\bdatabase\x12\x1e\n" +
	"\n" +
	"collection\x18\x02 \x01(\tR\n" +
	"collection\x12\x1f\n" +
	"\vinserted_id\x18\x03 \x01(\tR\n" +
	"insertedId\"R\n" +
	"\x14FindDocumentsRequest\x12\x1a\n" +
	"\bdatabase\x18\x01 \x01(\tR\bdatabase\x12\x1e\n" +
	"\n" +
	"collection\x18\x02 \x01(\tR\n" +
	"collection\"\x9f\x01\n" +
	"\rMongoDocument\x12;\n" +
	"\x06fields\x18\x01 \x03(\v2#.dbrouter.MongoDocument.FieldsEntryR\x06fields\x1aQ\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05value:\x028\x01\"\xa0\x01\n" +
	"\x15FindDocumentsResponse\x12\x1a\n" +
	"\bdatabase\x18\x01 \x01(\tR\bdatabase\x12\x1e\n" +
	"\n" +
	"collection\x18\x02 \x01(\tR\n" +
	"collection\x125\n" +
	"\tdocuments\x18\x03 \x03(\v2\x17.dbrouter.MongoDocumentR\tdocuments\x12\x14\n" +
	"\x05count\x18\x04 \x01(\x03R\x05count\"\x94\x01\n" +
	"\x15UpdateDocumentRequest\x12\x1a\n" +
	"\bdatabase\x18\x01 \x01(\tR\bdatabase\x12\x1e\n" +
	"\n" +
	"collection\x18\x02 \x01(\tR\n" +
	"collection\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\x12/\n" +
	"\x06update\x18\x04 \x01(\v2\x17.google.protobuf.StructR\x06update\"\xa0\x01\n" +
	"\x16UpdateDocumentResponse\x12\x1a\n" +
	"\bdatabase\x18\x01 \x01(\tR\bdatabase\x12\x1e\n" +
	"\n" +
	"collection\x18\x02 \x01(\tR\n" +
	"collection\x12#\n" +
	"\rmatched_count\x18\x03 \x01(\x03R\fmatchedCount\x12%\n" +
	"\x0emodified_count\x18\x04 \x01(\x03R\rmodifiedCount\"c\n" +
	"\x15DeleteDocumentRequest\x12\x1a\n" +
	"\bdatabase\x18\x01 \x01(\tR\bdatabase\x12\x1e\n" +
	"\n" +
	"collection\x18\x02 \x01(\tR\n" +
	"collection\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\"y\n" +
	"\x16DeleteDocumentResponse\x12\x1a\n" +
	"\bdatabase\x18\x01 \x01(\tR\bdatabase\x12\x1e\n" +
	"\n" +
	"collection\x18\x02 \x01(\tR\n" +
	"collection\x12#\n" +
	"\rdeleted_count\x18\x03 \x01(\x03R\fdeletedCount\"+\n" +
	"\x0fListKeysRequest\x12\x18\n" +
	"\apattern\x18\x01 \x01(\tR\apattern\"<\n" +
	"\x10ListKeysResponse\x12\x12\n" +
	"\x04keys\x18\x01 \x03(\tR\x04keys\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\"K\n" +
	"\x0fSetValueRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x10\n" +
	"\x03ttl\x18\x03 \x01(\x05R\x03ttl\"L\n" +
	"\x10SetValueResponse\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x10\n" +
	"\x03ttl\x18\x03 \x01(\x05R\x03ttl\"#\n" +
	"\x0fGetValueRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"L\n" +
	"\x10GetValueResponse\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x10\n" +
	"\x03ttl\x18\x03 \x01(\x05R\x03ttl\"$\n" +
	"\x10DeleteKeyRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"?\n" +
	"\x11DeleteKeyResponse\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x18\n" +
	"\adeleted\x18\x02 \x01(\bR\adeleted\"\x12\n" +
	"\x10RedisInfoRequest\"@\n" +
	"\x11RedisInfoResponse\x12\x17\n" +
	"\adb_size\x18\x01 \x01(\x03R\x06dbSize\x12\x12\n" +
	"\x04info\x18\x02 \x01(\tR\x04info2\xb0\x02\n" +
	"\rHealthService\x12D\n" +
	"\x05Check\x12\x1c.dbrouter.HealthCheckRequest\x1a\x1d.dbrouter.HealthCheckResponse\x12I\n" +
	"\rCheckPostgres\x12\x1c.dbrouter.HealthCheckRequest\x1a\x1a.dbrouter.ConnectionStatus\x12F\n" +
	"\n" +
	"CheckMongo\x12\x1c.dbrouter.HealthCheckRequest\x1a\x1a.dbrouter.ConnectionStatus\x12F\n" +
	"\n" +
	"CheckRedis\x12\x1c.dbrouter.HealthCheckRequest\x1a\x1a.dbrouter.ConnectionStatus2\xf4\x04\n" +
	"\x0fPostgresService\x12P\n" +
	"\rListDatabases\x12\x1e.dbrouter.ListDatabasesRequest\x1a\x1f.dbrouter.ListDatabasesResponse\x12S\n" +
	"\x0eCreateDatabase\x12\x1f.dbrouter.CreateDatabaseRequest\x1a .dbrouter.CreateDatabaseResponse\x12G\n" +
	"\n" +
	"ListTables\x12\x1b.dbrouter.ListTablesRequest\x1a\x1c.dbrouter.ListTablesResponse\x12M\n" +
	"\fExecuteQuery\x12\x1d.dbrouter.ExecuteQueryRequest\x1a\x1e.dbrouter.ExecuteQueryResponse\x12G\n" +
	"\n" +
	"SelectData\x12\x1b.dbrouter.SelectDataRequest\x1a\x1c.dbrouter.SelectDataResponse\x12G\n" +
	"\n" +
	"InsertData\x12\x1b.dbrouter.InsertDataRequest\x1a\x1c.dbrouter.InsertDataResponse\x12G\n" +
	"\n" +
	"UpdateData\x12\x1b.dbrouter.UpdateDataRequest\x1a\x1c.dbrouter.UpdateDataResponse\x12G\n" +
	"\n" +
	"DeleteData\x12\x1b.dbrouter.DeleteDataRequest\x1a\x1c.dbrouter.DeleteDataResponse2\x93\x04\n" +
	"\fMongoService\x12Z\n" +
	"\rListDatabases\x12#.dbrouter.ListMongoDatabasesRequest\x1a$.dbrouter.ListMongoDatabasesResponse\x12V\n" +
	"\x0fListCollections\x12 .dbrouter.ListCollectionsRequest\x1a!.dbrouter.ListCollectionsResponse\x12S\n" +
	"\x0eInsertDocument\x12\x1f.dbrouter.InsertDocumentRequest\x1a .dbrouter.InsertDocumentResponse\x12P\n" +
	"\rFindDocuments\x12\x1e.dbrouter.FindDocumentsRequest\x1a\x1f.dbrouter.FindDocumentsResponse\x12S\n" +
	"\x0eUpdateDocument\x12\x1f.dbrouter.UpdateDocumentRequest\x1a .dbrouter.UpdateDocumentResponse\x12S\n" +
	"\x0eDeleteDocument\x12\x1f.dbrouter.DeleteDocumentRequest\x1a .dbrouter.DeleteDocumentResponse2\xde\x02\n" +
	"\fRedisService\x12A\n" +
	"\bListKeys\x12\x19.dbrouter.ListKeysRequest\x1a\x1a.dbrouter.ListKeysResponse\x12A\n" +
	"\bSetValue\x12\x19.dbrouter.SetValueRequest\x1a\x1a.dbrouter.SetValueResponse\x12A\n" +
	"\bGetValue\x12\x19.dbrouter.GetValueRequest\x1a\x1a.dbrouter.GetValueResponse\x12D\n" +
	"\tDeleteKey\x12\x1a.dbrouter.DeleteKeyRequest\x1a\x1b.dbrouter.DeleteKeyResponse\x12?\n" +
	"\x04Info\x12\x1a.dbrouter.RedisInfoRequest\x1a\x1b.dbrouter.RedisInfoResponseB\x1aZ\x18db-router/proto/dbrouterb\x06proto3"

var (
	file_dbrouter_proto_rawDescOnce sync.Once
	file_dbrouter_proto_rawDescData []byte
)

func file_dbrouter_proto_rawDescGZIP() []byte {
	file_dbrouter_proto_rawDescOnce.Do(func() {
		file_dbrouter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dbrouter_proto_rawDesc), len(file_dbrouter_proto_rawDesc)))
	})
	return file_dbrouter_proto_rawDescData
}

var file_dbrouter_proto_msgTypes = make([]protoimpl.MessageInfo, 47)
var file_dbrouter_proto_goTypes = []any{
	(*HealthCheckRequest)(nil),         // 0: dbrouter.HealthCheckRequest
	(*ConnectionStatus)(nil),           // 1: dbrouter.ConnectionStatus
	(*HealthCheckResponse)(nil),        // 2: dbrouter.HealthCheckResponse
	(*ListDatabasesRequest)(nil),       // 3: dbrouter.ListDatabasesRequest
	(*ListDatabasesResponse)(nil),      // 4: dbrouter.ListDatabasesResponse
	(*CreateDatabaseRequest)(nil),      // 5: dbrouter.CreateDatabaseRequest
	(*CreateDatabaseResponse)(nil),     // 6: dbrouter.CreateDatabaseResponse
	(*ListTablesRequest)(nil),          // 7: dbrouter.ListTablesRequest
	(*ListTablesResponse)(nil),         // 8: dbrouter.ListTablesResponse
	(*ExecuteQueryRequest)(nil),        // 9: dbrouter.ExecuteQueryRequest
	(*QueryResultRow)(nil),             // 10: dbrouter.QueryResultRow
	(*ExecuteQueryResponse)(nil),       // 11: dbrouter.ExecuteQueryResponse
	(*SelectDataRequest)(nil),          // 12: dbrouter.SelectDataRequest
	(*SelectDataResponse)(nil),         // 13: dbrouter.SelectDataResponse
	(*InsertDataRequest)(nil),          // 14: dbrouter.InsertDataRequest
	(*InsertDataResponse)(nil),         // 15: dbrouter.InsertDataResponse
	(*UpdateDataRequest)(nil),          // 16: dbrouter.UpdateDataRequest
	(*UpdateDataResponse)(nil),         // 17: dbrouter.UpdateDataResponse
	(*DeleteDataRequest)(nil),          // 18: dbrouter.DeleteDataRequest
	(*DeleteDataResponse)(nil),         // 19: dbrouter.DeleteDataResponse
	(*ListMongoDatabasesRequest)(nil),  // 20: dbrouter.ListMongoDatabasesRequest
	(*ListMongoDatabasesResponse)(nil), // 21: dbrouter.ListMongoDatabasesResponse
	(*ListCollectionsRequest)(nil),     // 22: dbrouter.ListCollectionsRequest
	(*ListCollectionsResponse)(nil),    // 23: dbrouter.ListCollectionsResponse
	(*InsertDocumentRequest)(nil),      // 24: dbrouter.InsertDocumentRequest
	(*InsertDocumentResponse)(nil),     // 25: dbrouter.InsertDocumentResponse
	(*FindDocumentsRequest)(nil),       // 26: dbrouter.FindDocumentsRequest
	(*MongoDocument)(nil),              // 27: dbrouter.MongoDocument
	(*FindDocumentsResponse)(nil),      // 28: dbrouter.FindDocumentsResponse
	(*UpdateDocumentRequest)(nil),      // 29: dbrouter.UpdateDocumentRequest
	(*UpdateDocumentResponse)(nil),     // 30: dbrouter.UpdateDocumentResponse
	(*DeleteDocumentRequest)(nil),      // 31: dbrouter.DeleteDocumentRequest
	(*DeleteDocumentResponse)(nil),     // 32: dbrouter.DeleteDocumentResponse
	(*ListKeysRequest)(nil),            // 33: dbrouter.ListKeysRequest
	(*ListKeysResponse)(nil),           // 34: dbrouter.ListKeysResponse
	(*SetValueRequest)(nil),            // 35: dbrouter.SetValueRequest
	(*SetValueResponse)(nil),           // 36: dbrouter.SetValueResponse
	(*GetValueRequest)(nil),            // 37: dbrouter.GetValueRequest
	(*GetValueResponse)(nil),           // 38: dbrouter.GetValueResponse
	(*DeleteKeyRequest)(nil),           // 39: dbrouter.DeleteKeyRequest
	(*DeleteKeyResponse)(nil),          // 40: dbrouter.DeleteKeyResponse
	(*RedisInfoRequest)(nil),           // 41: dbrouter.RedisInfoRequest
	(*RedisInfoResponse)(nil),          // 42: dbrouter.RedisInfoResponse
	nil,                                // 43: dbrouter.QueryResultRow.FieldsEntry
	nil,                                // 44: dbrouter.InsertDataRequest.DataEntry
	nil,                                // 45: dbrouter.UpdateDataRequest.DataEntry
	nil,                                // 46: dbrouter.MongoDocument.FieldsEntry
	(*structpb.Struct)(nil),            // 47: google.protobuf.Struct
	(*structpb.Value)(nil),             // 48: google.protobuf.Value
}
var file_dbrouter_proto_depIdxs = []int32{
	1,  // 0: dbrouter.HealthCheckResponse.postgres:type_name -> dbrouter.ConnectionStatus
	1,  // 1: dbrouter.HealthCheckResponse.mongo:type_name -> dbrouter.ConnectionStatus
	1,  // 2: dbrouter.HealthCheckResponse.redis:type_name -> dbrouter.ConnectionStatus
	43, // 3: dbrouter.QueryResultRow.fields:type_name -> dbrouter.QueryResultRow.FieldsEntry
	10, // 4: dbrouter.ExecuteQueryResponse.rows:type_name -> dbrouter.QueryResultRow
	10, // 5: dbrouter.SelectDataResponse.data:type_name -> dbrouter.QueryResultRow
	44, // 6: dbrouter.InsertDataRequest.data:type_name -> dbrouter.InsertDataRequest.DataEntry
	45, // 7: dbrouter.UpdateDataRequest.data:type_name -> dbrouter.UpdateDataRequest.DataEntry
	47, // 8: dbrouter.InsertDocumentRequest.document:type_name -> google.protobuf.Struct
	46, // 9: dbrouter.MongoDocument.fields:type_name -> dbrouter.MongoDocument.FieldsEntry
	27, // 10: dbrouter.FindDocumentsResponse.documents:type_name -> dbrouter.MongoDocument
	47, // 11: dbrouter.UpdateDocumentRequest.update:type_name -> google.protobuf.Struct
	48, // 12: dbrouter.QueryResultRow.FieldsEntry.value:type_name -> google.protobuf.Value
	48, // 13: dbrouter.InsertDataRequest.DataEntry.value:type_name -> google.protobuf.Value
	48, // 14: dbrouter.UpdateDataRequest.DataEntry.value:type_name -> google.protobuf.Value
	48, // 15: dbrouter.MongoDocument.FieldsEntry.value:type_name -> google.protobuf.Value
	0,  // 16: dbrouter.HealthService.Check:input_type -> dbrouter.HealthCheckRequest
	0,  // 17: dbrouter.HealthService.CheckPostgres:input_type -> dbrouter.HealthCheckRequest
	0,  // 18: dbrouter.HealthService.CheckMongo:input_type -> dbrouter.HealthCheckRequest
	0,  // 19: dbrouter.HealthService.CheckRedis:input_type -> dbrouter.HealthCheckRequest
	3,  // 20: dbrouter.PostgresService.ListDatabases:input_type -> dbrouter.ListDatabasesRequest
	5,  // 21: dbrouter.PostgresService.CreateDatabase:input_type -> dbrouter.CreateDatabaseRequest
	7,  // 22: dbrouter.PostgresService.ListTables:input_type -> dbrouter.ListTablesRequest
	9,  // 23: dbrouter.PostgresService.ExecuteQuery:input_type -> dbrouter.ExecuteQueryRequest
	12, // 24: dbrouter.PostgresService.SelectData:input_type -> dbrouter.SelectDataRequest
	14, // 25: dbrouter.PostgresService.InsertData:input_type -> dbrouter.InsertDataRequest
	16, // 26: dbrouter.PostgresService.UpdateData:input_type -> dbrouter.UpdateDataRequest
	18, // 27: dbrouter.PostgresService.DeleteData:input_type -> dbrouter.DeleteDataRequest
	20, // 28: dbrouter.MongoService.ListDatabases:input_type -> dbrouter.ListMongoDatabasesRequest
	22, // 29: dbrouter.MongoService.ListCollections:input_type -> dbrouter.ListCollectionsRequest
	24, // 30: dbrouter.MongoService.InsertDocument:input_type -> dbrouter.InsertDocumentRequest
	26, // 31: dbrouter.MongoService.FindDocuments:input_type -> dbrouter.FindDocumentsRequest
	29, // 32: dbrouter.MongoService.UpdateDocument:input_type -> dbrouter.UpdateDocumentRequest
	31, // 33: dbrouter.MongoService.DeleteDocument:input_type -> dbrouter.DeleteDocumentRequest
	33, // 34: dbrouter.RedisService.ListKeys:input_type -> dbrouter.ListKeysRequest
	35, // 35: dbrouter.RedisService.SetValue:input_type -> dbrouter.SetValueRequest
	37, // 36: dbrouter.RedisService.GetValue:input_type -> dbrouter.GetValueRequest
	39, // 37: dbrouter.RedisService.DeleteKey:input_type -> dbrouter.DeleteKeyRequest
	41, // 38: dbrouter.RedisService.Info:input_type -> dbrouter.RedisInfoRequest
	2,  // 39: dbrouter.HealthService.Check:output_type -> dbrouter.HealthCheckResponse
	1,  // 40: dbrouter.HealthService.CheckPostgres:output_type -> dbrouter.ConnectionStatus
	1,  // 41: dbrouter.HealthService.CheckMongo:output_type -> dbrouter.ConnectionStatus
	1,  // 42: dbrouter.HealthService.CheckRedis:output_type -> dbrouter.ConnectionStatus
	4,  // 43: dbrouter.PostgresService.ListDatabases:output_type -> dbrouter.ListDatabasesResponse
	6,  // 44: dbrouter.PostgresService.CreateDatabase:output_type -> dbrouter.CreateDatabaseResponse
	8,  // 45: dbrouter.PostgresService.ListTables:output_type -> dbrouter.ListTablesResponse
	11, // 46: dbrouter.PostgresService.ExecuteQuery:output_type -> dbrouter.ExecuteQueryResponse
	13, // 47: dbrouter.PostgresService.SelectData:output_type -> dbrouter.SelectDataResponse
	15, // 48: dbrouter.PostgresService.InsertData:output_type -> dbrouter.InsertDataResponse
	17, // 49: dbrouter.PostgresService.UpdateData:output_type -> dbrouter.UpdateDataResponse
	19, // 50: dbrouter.PostgresService.DeleteData:output_type -> dbrouter.DeleteDataResponse
	21, // 51: dbrouter.MongoService.ListDatabases:output_type -> dbrouter.ListMongoDatabasesResponse
	23, // 52: dbrouter.MongoService.ListCollections:output_type -> dbrouter.ListCollectionsResponse
	25, // 53: dbrouter.MongoService.InsertDocument:output_type -> dbrouter.InsertDocumentResponse
	28, // 54: dbrouter.MongoService.FindDocuments:output_type -> dbrouter.FindDocumentsResponse
	30, // 55: dbrouter.MongoService.UpdateDocument:output_type -> dbrouter.UpdateDocumentResponse
	32, // 56: dbrouter.MongoService.DeleteDocument:output_type -> dbrouter.DeleteDocumentResponse
	34, // 57: dbrouter.RedisService.ListKeys:output_type -> dbrouter.ListKeysResponse
	36, // 58: dbrouter.RedisService.SetValue:output_type -> dbrouter.SetValueResponse
	38, // 59: dbrouter.RedisService.GetValue:output_type -> dbrouter.GetValueResponse
	40, // 60: dbrouter.RedisService.DeleteKey:output_type -> dbrouter.DeleteKeyResponse
	42, // 61: dbrouter.RedisService.Info:output_type -> dbrouter.RedisInfoResponse
	39, // [39:62] is the sub-list for method output_type
	16, // [16:39] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_dbrouter_proto_init() }
func file_dbrouter_proto_init() {
	if File_dbrouter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dbrouter_proto_rawDesc), len(file_dbrouter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   47,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_dbrouter_proto_goTypes,
		DependencyIndexes: file_dbrouter_proto_depIdxs,
		MessageInfos:      file_dbrouter_proto_msgTypes,
	}.Build()
	File_dbrouter_proto = out.File
	file_dbrouter_proto_goTypes = nil
	file_dbrouter_proto_depIdxs = nil
}
